var appConfig = {
  "locale": "SE",
  "hotelPageURL": "/hotelonlylist",
  "sheetID": "15g8HTva7VtMT7hviLU7Vfqt7abYiokZV9eVsxy3Vroo",
  "dateFormat": "YYYYMMDD",
  "tableLayout": {
    "opponent": "Motståndare",
    "matchdate": "Matchdatum",
    "months": ["jan","feb","mar","apr","maj","jun","jul","aug","sep","okt","nov","dec"],
    "days": ["Sön","Mån","Tis","Ons","Tor","Fre","Lör"]
  },
  "bookingText": {
    "adults": "Vuxna",
    "children": "Barn (0-17 år)",
    "childAge": "Barnets ålder",
    "choose": "Välj",
    "buttonText": "Sök pris och beställ",
    "year": "år",
    "hotelNights": "Önsker du flera hotellnätter? Kontakta oss via e-post med beställningsnummer och datum när du har genomfört din beställning.",
    "childAgeError": "Ange barnens ålder",
    "membershipError": "Du behöver godkänna villkoren",
    "soldout": "Slutsåld"
  },
  "teams": {
    "manchester-united": {
      "teamCode": "MUFC",
      "pagenr": 7,
      "ctryid": 73,
			"resid": 380,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av Manchester United.",
			"membership" : true,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "MAN"
    },
    "liverpool": {
      "teamCode": "LPL",
      "teamName": "Liverpool FC",
      "pagenr": 6,
      "ctryid": 73,
			"resid": 564,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av Liverpool F.C",
			"membership" : true,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "LPL"
    },
    "chelsea": {
      "teamCode": "CFC",
      "teamName": "Chelsea FC",
      "pagenr": 8,
      "ctryid": 73,
			"resid": 26798,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av Chelsea.",
			"membership" : true,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XLC"
    },
    "tottenham-hotspur": {
      "teamCode": "THFC",
      "teamName": "Tottenham Hotspurs",
      "pagenr": 9,
      "ctryid": 73,
			"resid": 58471,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av Tottenham.",
			"membership" : true,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XLT"
    },
    "west-ham": {
      "teamCode": "WHUFC",
      "teamName": "West Ham",
      "pagenr": 12,
      "ctryid": 73,
			"resid": 101882,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av West Ham.",
			"membership" : true,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XLW"
	},
    "manchester-city": {
      "teamCode": "MCFC",
      "teamName": "Manchester City",
      "pagenr": 14,
      "ctryid": 73,
			"resid": 67629,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av Manchester City.",
			"membership" : true,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XMC"
	},
    "barcelona": {
      "teamCode": "FCB",
      "teamName": "Barcelona",
      "pagenr": 10,
      "ctryid": 65,
			"resid": 68957,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av FC Barcelona.",
			"membership" : false,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XBA"
    },
    "real-madrid": {
      "teamCode": "XMA",
      "teamName": "Real Madrid",
      "pagenr": 11,
      "ctryid": 65,
			"resid": 70188,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av Real Madrid.",
			"membership" : false,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XMA"
    },
    "atletico-madrid": {
      "teamCode": "XAM",
      "teamName": "Atletico Madrid",
      "pagenr": 15,
      "ctryid": 65,
			"resid": 108146,
			"membershipText": "Jag är medveten om att hela resesällskapet måste vara supporters av Atletico Madrid.",
			"membership" : false,
			"basis": "2 nätter",
			"full": "3 nätter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XAM"
    }
  }
}
