var appConfig = {
  "locale": "DK",
  "hotelPageURL": "/kunhotel-soege-resultat",
  "sheetID": "1uiHcGRU5DTV_4aLk15Uzf-vi-aTj0CdQtkJHeM-zh1Y",
  "dateFormat": "YYYYMMDD",
  "tableLayout": {
    "opponent": "Modstander",
    "matchdate": "Kampdato",
    "months": ["jan","feb","mar","apr","maj","jun","jul","aug","sep","okt","nov","dec"],
    "days": ["Søn","Man","Tir","Ons","Tor","Fre","Lør"]
  },
  "bookingText": {
    "adults": "Voksne",
    "children": "Børn (0-17 år)",
    "childAge": "Vælg alder",
    "choose": "Vælg",
    "buttonText": "Find pris og bestil",
    "year": "år",
    "hotelNights": "Ønsker du flere hotelnætter? Send os en e-mail med bestillingsnummer og datoer når du har gennemført bestillingen.",
    "childAgeError": "Angiv alder på børn",
    "membershipError": "Du må samtykke til vilkårene",
    "soldout": "Udsolgt"
  },
  "teams": {
    "manchester-united": { // team URL
      "teamCode": "MUFC",
      "pagenr": 2,
      "ctryid": 6749,
			"resid": 58301,
			"membershipText": "Jeg samtykker til krav om at alle rejsende er supportere af Manchester United.",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": true,
			"img": "MAN"
    },
    "liverpool": {
      "teamCode": "LPL",
      "teamName": "Liverpool FC",
      "pagenr": 1,
      "ctryid": 6749,
			"resid": 58299,
			"membershipText": "Jeg samtykker til krav om medlemskap i Liverpool F.C. Supporters' Club Norway Branch for alle rejsende",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": true,
			"img": "LPL"
    },
    "chelsea": {
      "teamCode": "CFC",
      "teamName": "Chelsea FC",
      "pagenr": 3,
      "ctryid": 6749,
			"resid": 57949,
			"membershipText": "Jeg samtykker til krav om at alle rejsende er supportere af Chelsea.",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": true,
			"img": "XLC"
    },
    "tottenham": {
      "teamCode": "THFC",
      "teamName": "Tottenham Hotspurs",
      "pagenr": 4,
      "ctryid": 6749,
			"resid": 58302,
			"membershipText": "Jeg samtykker til krav om medlemskap i Tottenhams Venner Norway.",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": true,
			"img": "XLT"
    },
    "west-ham": {
      "teamCode": "WHUFC",
      "teamName": "Westham",
      "pagenr": 8,
      "ctryid": 6749,
			"resid": 101898,
			"membershipText": "Jeg samtykker til krav om medlemskap i Westham.",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XLW"
    },
    "manchester-city": {
      "teamCode": "MCFC",
      "teamName": "Manchester City",
      "pagenr": 9,
      "ctryid": 6749,
			"resid": 67542,
			"membershipText": "Jeg samtykker til krav om medlemskap.",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "Salget starter 3. august",
      "inSale": false,
			"img": "XMC"
    },
    "fc-barcelona": {
      "teamCode": "FCB",
      "teamName": "FC Barcelona",
      "pagenr": 5,
      "ctryid": 4826,
			"resid": 69884,
			"membershipText": "Jeg samtykker til krav om medlemskap.",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "Salget starter 5. august",
      "inSale": false,
			"img": "XBA"
    },
    "real-madrid": {
      "teamCode": "XMA",
      "teamName": "Real Madrid",
      "pagenr": 6,
      "ctryid": 4826,
			"resid": 69970,
			"membershipText": "Jeg samtykker til krav om medlemskap.",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "Salget starter 5. august",
      "inSale": false,
			"img": "XMA"
    },
    "atletico-madrid": {
      "teamCode": "XAM",
      "teamName": "Atletico Madrid",
      "pagenr": 10,
      "ctryid": 4826,
			"resid": 108012,
			"membershipText": "Jeg samtykker til krav om medlemskap.",
			"membership" : false,
			"basis": "2 nætter",
			"full": "3 nætter",
      "salesInfo": "",
      "salesInfoMore": "Salget starter midt i august",
      "inSale": false,
			"img": "XAM"
    }
  }
}
