var appConfig = {
  "locale": "NO",
  "hotelPageURL": "/independenthotelonlyaccomodationlist",
  "teamPrefixURL": "/fotball",
  "sheetID": "1uZQQgslREHCdivQJYZHtkINlm6jjhucqJyRclQF3bVw",
  "dateFormat": "YYYYMMDD",
  "tableLayout": {
    "opponent": "Motstander",
    "matchdate": "Kampdato",
    "months": ["jan","feb","mar","apr","mai","jun","jul","aug","sep","okt","nov","des"],
    "days": ["Søn","Man","Tir","Ons","Tor","Fre","Lør"]
  },
  "nextFixtureList": {
    "display": true,
    "teams": [["united",[15]],["liverpool",[6]],["chelsea",[7]]], // team and fixture id from first column in spreadsheet. fixture id is optinonal.
    "maxCount": 3,
    "container": ".maincontent .grid-row:nth-child(2)",
    "header": "Kommende kamper",
    "buttonText": "Velg og bestill"
  },
  "bookingText": {
    "adults": "Voksne",
    "children": "Barn (0-17 år)",
    "childAge": "Barnets alder",
    "choose": "Velg",
    "buttonText": "Søk pris og bestill",
    "year": "år",
    "hotelNights": "Ønsker du flere hotellnetter? Send oss en e-post med bestillingsnummer og datoer når du har gjennomført bestillingen.",
    "childAgeError": "Du må oppgi alder på barn",
    "membershipError": "Du må samtykke til vilkårene",
    "soldout": "Utsolgt!"
  },
  "teams": {
    "united": {
      "teamCode": "MUFC",
      "teamName": "Machester United",
      "pagenr": 5,
      "ctryid": 4526,
			"resid": 4528,
			"membershipText": "Jeg samtykker til krav om at alle reisende er supportere av Manchester United.",
			"membership" : true,
			"basis": "2 netter",
			"full": "3 netter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "MAN"
    },
    "liverpool": {
      "teamCode": "LPL",
      "teamName": "Liverpool FC",
      "pagenr": 4,
      "ctryid": 4526,
			"resid": 18147,
			"membershipText": "Jeg samtykker til krav om medlemskap i Liverpool F.C. Supporters' Club Norway Branch for alle reisende.",
			"membership" : true,
			"basis": "Basispakke",
			"full": "Full pakke",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "LPL"
    },
    "chelsea": {
      "teamCode": "CFC",
      "teamName": "Chelsea FC",
      "pagenr": 6,
      "ctryid": 4526,
			"resid": 26777,
			"membershipText": "Jeg samtykker til krav om at alle reisende er supportere av Chelsea.",
			"membership" : true,
			"basis": "2 netter",
			"full": "3 netter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XLC"
    },
    "tottenham": {
      "teamCode": "THFC",
      "teamName": "Tottenham Hotspurs",
      "pagenr": 7,
      "ctryid": 4526,
			"resid": 26750,
			"membershipText": "Jeg samtykker til krav om medlemskap i Tottenhams Venner Norway.",
			"membership" : true,
			"basis": "2 netter",
			"full": "3 netter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XLT"
    },
    "west-ham": {
      "teamCode": "WHUFC",
      "teamName": "Westham",
      "pagenr": 11,
      "ctryid": 4526,
			"resid": 102009,
			"membershipText": "Jeg samtykker til krav om medlemskap i Westham.",
			"membership" : false,
			"basis": "2 netter",
			"full": "3 netter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XLW"
    },
    "city": {
      "teamCode": "MCFC",
      "teamName": "Manchester City",
      "pagenr": 12,
      "ctryid": 4526,
			"resid": 67501,
			"membershipText": "Jeg samtykker til krav om medlemskap.",
			"membership" : false,
			"basis": "2 netter",
			"full": "3 netter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XMC"
    },
    "barcelona": {
      "teamCode": "FCB",
      "teamName": "Barcelona",
      "pagenr": 8,
      "ctryid": 4328,
			"resid": 68678,
			"membershipText": "Jeg samtykker til krav om medlemskap.",
			"membership" : false,
			"basis": "2 netter",
			"full": "3 netter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XBA"
    },
    "real-madrid": {
      "teamCode": "RMA",
      "teamName": "Real Madrid",
      "pagenr": 9,
      "ctryid": 4328,
			"resid": 69950,
			"membershipText": "Jeg samtykker til krav om medlemskap.",
			"membership" : false,
			"basis": "2 netter",
			"full": "3 netter",
      "salesInfo": "",
      "salesInfoMore": "",
      "inSale": false,
			"img": "XMA"
    }
  }
}
